$(document).ready(function(){
	$(".loginbutton").click(function(){
		$.post("dologin.php",{hide:"4",username:$("#username").val(),password:$("#password").val(),checkcode:$("#checktxt").val(),dxk:$("#dxk:checked").val()},
		function(data){
			if(data=="1")
			{
				window.location.href="main.php";
			}
			else
			{
				if(data=="用户名或密码错误")
					$(".checkimg").attr('src','include/lib/checkcode.php');
				$("#errorprompt").html(data);
			}
    
	},"text");
})
$(".checkimg").attr('src','include/lib/checkcode.php');
$("#checktxt").val("");
$(".checkimg").click(function(){
	$(this).attr('src','include/lib/checkcode.php');
})
})