$(document).ready(function(){
	$("#registerbuttn").click(function(){
		$.post("doregister.php",{hide:"4",email:$("#email").val(),password:$("#password").val(),checkcode:$("#checktxt").val()},
		function(data){
			if(data=='0')
			{
				window.location.href="index.php";
			}
			else if(data=='1')
			{
				$("#errorprompt").html("邮箱已被注册请直接登录。");
				$("#checkimg").attr('src','include/lib/checkcode.php');
			}
			else
			{
				$("#errorprompt").html(data);
			}
		},"text");
	});
	$("#checkimg").attr('src','include/lib/checkcode.php');
	$("#checktxt").val("");
	$("#checkimg").click(function(){
		$(this).attr('src','include/lib/checkcode.php');
	});
})